# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'whale-ios-trevin' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for whale-ios-trevin
  pod 'Alamofire'

  target 'whale-ios-trevinTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'whale-ios-trevinUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
